spring.application.name=ksc

spring.config.import=optional:configserver:${CONFIG_SERVER_URI:http://localhost:7000/}
spring.profiles.active=${PROFILE:default}

# ===============================
# REDIS COMMON
# ===============================

# Redis Connection
spring.redis.host=72.61.144.159
spring.redis.port=6379
spring.redis.password=passwd@2026

# ===============================
# KAFKA COMMON
# ===============================
spring.kafka.bootstrap-servers=72.61.144.159:9092


